# Generated by Django 4.2.20 on 2025-04-09 02:21

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
