# Generated by Django 4.2.20 on 2025-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Main Service', 'verbose_name_plural': 'Main Services'},
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='how_it_works_title',
        ),
        migrations.AddField(
            model_name='mainservice',
            name='benefits_subtitle',
            field=models.TextField(default='Experience the advantages of working with a professional cleaning service.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='choose_service_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/service_images/'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='choose_service_subtitle',
            field=models.TextField(default="We understand that selecting the perfect cleaning service is crucial. Here's what makes our service stand out and how we can help you make the right choice."),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='choose_service_title',
            field=models.CharField(default='Choosing the Right Cleaning Service', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='considerations_subtitle',
            field=models.TextField(default='Important aspects that make our cleaning service stand out from the rest.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='cta_button_text',
            field=models.CharField(default='Schedule Cleaning', max_length=100),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='cta_secondary_button_text',
            field=models.CharField(default='Get a Quote', max_length=100),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='cta_subtitle',
            field=models.TextField(default='Experience the difference with our professional cleaning services. Book now and enjoy a spotless environment.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='cta_title',
            field=models.CharField(default='Ready for a Cleaner Space?', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='faqs_subtitle',
            field=models.TextField(default='Find answers to common questions about our service.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='faqs_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='features_subtitle',
            field=models.TextField(default='Explore our comprehensive range of services designed to meet your specific needs and requirements.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='how_to_book_subtitle',
            field=models.TextField(default='Getting started with our service is simple and straightforward. Follow these easy steps to book your cleaning service.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='how_to_book_title',
            field=models.CharField(default='How to Book Our Service', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='hyperlinks_subtitle',
            field=models.TextField(default='Explore our comprehensive range of services and helpful resources.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='hyperlinks_title',
            field=models.CharField(default='Related Services & Resources', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='ideal_for_subtitle',
            field=models.TextField(default='Our services are perfectly suited for various situations and requirements'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='ideal_for_title',
            field=models.CharField(default='Ideal For', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='lead_form_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/service_images/'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='lead_form_subtitle',
            field=models.TextField(default='Fill out this form, and our team will contact you shortly.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='lead_form_title',
            field=models.CharField(default='Get a Free Quote Today', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='service_types_subtitle',
            field=models.TextField(default='Choose from our range of specialized services tailored to meet your specific needs and requirements.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='service_types_title',
            field=models.CharField(default='Comprehensive Home Care Services', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='specialized_services_subtitle',
            field=models.TextField(default='Explore our specialized services tailored to meet your unique requirements and preferences.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='stats_subtitle',
            field=models.TextField(default='We bring years of expertise and dedication to every service we provide, ensuring your complete satisfaction and peace of mind.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='stats_title',
            field=models.CharField(default='Experience Excellence with Our Services', max_length=200),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='why_hire_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/service_images/'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='why_hire_subtitle',
            field=models.TextField(default='Experience unmatched quality and reliability with our professional services. We go above and beyond to ensure your complete satisfaction.'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='why_hire_title',
            field=models.CharField(default='Why Choose Our Services', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='icon',
            field=models.CharField(help_text="FontAwesome class (e.g., 'fas fa-check')", max_length=50),
        ),
        migrations.AlterField(
            model_name='servicestat',
            name='icon',
            field=models.CharField(help_text="FontAwesome class (e.g., 'fas fa-star')", max_length=50),
        ),
    ]
