# Generated by Django 4.2.20 on 2025-05-23 07:26

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_specializedservicecard_servicetypecard_idealforcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='benefits_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the benefits section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='choose_service_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the choose service section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='considerations_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the considerations section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='cta_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the CTA section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='features_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the features section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='how_to_book_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the how to book section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='ideal_for_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the ideal for section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='service_types_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the service types section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='specialized_services_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the specialized services section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='stats_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the stats section'),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='why_hire_bottom_paragraph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional text to appear below the why hire us section'),
        ),
    ]
