# Generated by Django 4.2.20 on 2025-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_image_alter_services_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/images/ezyhelpers.png', upload_to='static/blog_images/'),
        ),
    ]
