# Generated by Django 4.2.20 on 2025-05-26 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mainservice_benefits_bottom_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='benefits_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='benefits_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='choose_service_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='choose_service_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='considerations_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='cta_button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='cta_secondary_button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='cta_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='cta_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='faqs_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='faqs_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='features_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='how_to_book_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='how_to_book_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='hyperlinks_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='hyperlinks_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='ideal_for_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='ideal_for_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='lead_form_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='lead_form_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='service_types_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='service_types_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='specialized_services_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='specialized_services_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='stats_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='stats_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='why_hire_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='why_hire_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
        ),
    ]
