# Generated by Django 4.2.20 on 2025-04-30 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_reading_time_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(upload_to='static/service_images/')),
                ('hero_rating', models.DecimalField(decimal_places=2, default=4.98, max_digits=3)),
                ('features_title', models.CharField(max_length=200)),
                ('how_it_works_title', models.CharField(max_length=200)),
                ('how_it_works_description', ckeditor.fields.RichTextField()),
                ('benefits_title', models.CharField(max_length=200)),
                ('benefits_description', ckeditor.fields.RichTextField()),
                ('benefits_link_text', models.CharField(blank=True, max_length=100)),
                ('benefits_link_url', models.CharField(blank=True, max_length=200)),
                ('specialized_services_title', models.CharField(max_length=200)),
                ('specialized_services', ckeditor.fields.RichTextField()),
                ('considerations_title', models.CharField(max_length=200)),
                ('considerations', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faqs', models.ManyToManyField(to='main.faq')),
                ('features', models.ManyToManyField(to='main.servicefeature')),
                ('stats', models.ManyToManyField(to='main.servicestat')),
            ],
        ),
    ]
