# Generated by Django 4.2.20 on 2025-05-01 06:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_faq_servicefeature_servicestat_mainservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservice',
            name='how_it_works_description',
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='hero_subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='hero_title',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='servicestat',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(blank=True, help_text="Optional: FontAwesome class (e.g., 'fas fa-check')", max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works_steps', to='main.mainservice')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
