# Generated by Django 4.2.20 on 2025-05-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blog_slug_alter_mainservice_benefits_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='choose_service_image_alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='hero_image_alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='lead_form_image_alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='why_hire_image_alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
