# Generated by Django 4.2.20 on 2025-05-27 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainservice_choose_service_image_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetypecard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='specializedservicecard',
            name='image',
        ),
    ]
