# Generated by Django 4.2.20 on 2025-05-01 07:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_mainservice_how_it_works_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservice',
            name='benefits_description',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='considerations',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='specialized_services',
        ),
        migrations.CreateModel(
            name='SpecializedServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(blank=True, help_text='Optional: FontAwesome class', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_details', to='main.mainservice')),
            ],
        ),
        migrations.CreateModel(
            name='ConsiderationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_text', ckeditor.fields.RichTextField(help_text='The text for the consideration point.')),
                ('icon', models.CharField(blank=True, default='fas fa-info-circle', help_text='Optional: FontAwesome class (defaults to info icon)', max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consideration_points', to='main.mainservice')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(blank=True, help_text="Optional: FontAwesome class (e.g., 'fas fa-check-circle')", max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='main.mainservice')),
            ],
        ),
    ]
