# Generated by Django 4.2.20 on 2025-05-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_servicetypecard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome class (e.g., 'fas fa-check-circle')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us_points', to='main.mainservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChoosingRightPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome class (e.g., 'fas fa-check-circle')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choosing_right_points', to='main.mainservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
