# Generated by Django 4.2.20 on 2025-05-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mainservice_benefits_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the lead', max_length=255)),
                ('email', models.EmailField(help_text='Email address', max_length=255)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message or inquiry details')),
                ('source', models.CharField(choices=[('Homepage', 'Homepage Quick Quote'), ('Contact Us', 'Contact Us Page'), ('Service Page', 'Service Page Quote'), ('Other', 'Other')], help_text='Where the lead originated from', max_length=50)),
                ('service_needed', models.CharField(blank=True, help_text='Service requested (Homepage)', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Location provided (Homepage)', max_length=255, null=True)),
                ('timing', models.CharField(blank=True, help_text='When service is needed (Homepage)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
