# Generated by Django 4.2.20 on 2025-05-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_whychooseuspoint_choosingrightpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservice',
            name='cta_button_text',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='cta_secondary_button_text',
        ),
    ]
